# Generated by Django 4.0.5 on 2022-06-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='operation',
            new_name='Trade',
        ),
    ]
