# Generated by Django 4.0.5 on 2022-07-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbookapp', '0014_alter_trade_tradeimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='tradeimagen',
            field=models.ImageField(null=True, upload_to='tradesimg'),
        ),
        migrations.AlterField(
            model_name='tradeimagen',
            name='tradeimagen',
            field=models.ImageField(blank=True, null=True, upload_to='tradesimagen/'),
        ),
    ]
