# Generated by Django 4.0.5 on 2022-06-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=30, verbose_name='Simbolo')),
                ('posicion', models.PositiveSmallIntegerField(choices=[(1, 'Long'), (2, 'Short')], verbose_name='Posicion')),
                ('entrada', models.FloatField(verbose_name='Precio Entrada')),
                ('target', models.FloatField(verbose_name='Target')),
                ('stop', models.FloatField(verbose_name='stop')),
            ],
        ),
    ]
