# Generated by Django 4.0.5 on 2022-06-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbookapp', '0002_rename_operation_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='fecha',
            field=models.DateField(null=True, unique=True, verbose_name='Fecha de operacion'),
        ),
    ]
