# Generated by Django 4.0.5 on 2022-06-28 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbookapp', '0008_market_note_delete_mercados_delete_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='mercado',
        ),
        migrations.AddField(
            model_name='market',
            name='pais',
            field=models.CharField(default=datetime.datetime(2022, 6, 28, 16, 48, 32, 356697, tzinfo=utc), max_length=30, verbose_name='pais a donde pertenece'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='market',
            name='simbolo',
            field=models.CharField(max_length=30, verbose_name='Simbolo a observar'),
        ),
    ]
