# Generated by Django 4.0.5 on 2022-07-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingbookapp', '0013_trade_tradeimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='tradeimagen',
            field=models.ImageField(blank=True, null=True, upload_to='tradesimagen/'),
        ),
    ]
